### ISSUE TITLE
.tsx support

### ISSUE THREAD

**Issue by gustaff-weldon** [glato/emerge#11]
**Is your feature request related to a problem? Please describe.**

I'm trying to run `emerge` against a big React app codebase.
`python emerge.py -c frontend.yml`
```
---
project_name: frontend
loglevel: info
analyses:
- analysis_name: check_tsx_files
  source_directory: <some-project-path>/frontend/src
  only_permit_languages:
  - javascript
  only_permit_file_extensions:
  - .tsx
  - .ts
  ignore_dependencies_containing:
  - node_modules
  ignore_files_containing:
  - spec.ts
  - story.ts
  - mock.ts
  - .snap
  - .gql
  file_scan:
  - number_of_methods
  - source_lines_of_code
  - dependency_graph
  - louvain_modularity
  - fan_in_out
  export:
  - directory: <some-project-path>/frontend
  - graphml
  - dot
  - json
  - tabular_file
  - tabular_console_overall
  - d3
```

I'm getting tons and tons of messages: 
```
.tsx is an unknown extension, ignoring `/<edited>/src/Issues/Issues/Issues.tsx`
```
Pretty much the whole app gets skipped and not mapped.

**Describe the solution you'd like**
I'd like to be able to analyze a codebase that contains `tsx` which are essentially `jsx` with Typescript.

Given the size of our app, the ability to visualise it and check in an interactive way, would be an immense help.

**Comment by glato** [comment]
@gustaff-weldon Hi there, emerge currently tries to do a hybrid approach here: First it traverses recursively through all files from a starting directory and collecting every import statement within each file that it can find. For any recognized import statement, it tries to 'resolve' it to a correct POSIX-kind of filesystem path (e.g. an import of the kind  'foo/bar/../baz.ts' should be resolved to 'foo/baz.ts'). import aliases of the kind @myco/utils/date are currently not part of the resolver. If you say that this kind of import aliases are often used in js/ts project, this could indeed be an useful update. I'll see if I can find some further examples to analyze and test such import aliases and see about an update on this issue.

**Comment by gustaff-weldon** [comment]
@glato using aliases is quite a common thing in bigger JS projects. I will see if I can find some examples to help with testing

**Comment by glato** [comment]
@gustaff-weldon I've just pushed a small update in `0.19.2` that might solve your problems:

There is (currently) an undocumented yaml config section `replace_dependency_substrings` where you could easily define dependency name substring replacements like the following:

```yaml
replace_dependency_substrings:
- "@foo": src/foo
- "@bar": src/bar
```

so that import aliases/prefixes like `@foo` would be replaced by `src/foo` in any dependency. The only restriction here is that the import alias keyword is wrapped in `"..."` since this seems to be a YAML/PyYAML restriction also for some characters (including `@`).

This means that an example TS-configuration might look like this:

```yaml
---
project_name: tsx example
loglevel: info
analyses:
- analysis_name: simple check
  source_directory: /Users/user/github/cypress-realworld-app
  only_permit_languages:
  - javascript
  - typescript
  only_permit_file_extensions:
  - .js
  - .jsx
  - .ts
  - .tsx
  replace_dependency_substrings:
  - "@foo": src/foo
  - "@bar": src/bar
  file_scan:
  - number_of_methods
  - source_lines_of_code
  - dependency_graph
  - fan_in_out
  - louvain_modularity
  export:
  - directory: /Users/user/tmp/emerge/export/cypress-realworld-app
  - graphml
  - dot
  - json
  - tabular_file
  - tabular_console_overall
  - d3
```

I would appreciate any feedback if this might solve your problem (by defining a custom configuration in `replace_dependency_substrings`), then I would consider to also implement this for the other parsers.

**Comment by glato** [comment]
@gustaff-weldon I've release this import alias feature with version 1.0.0. You can also install this tool very quickly with pip now (pip install emerge-viz). Will be closing this issue in a couple of days if this solves the problem.

**Comment by gustaff-weldon** [comment]
@glato thanks, I will give it a go. I assume I should use the `replace_dependency_substrings:` workaround you have suggested.

**Comment by gustaff-weldon** [comment]
@glato I wonder if this is how the scan should behave given the following settings:
```
---
project_name: frontend
loglevel: debug
analyses:
- analysis_name: check_tsx_files
  source_directory: /Users/myuser/frontend/src
  only_permit_languages:
  - javascript
  - typescript
  only_permit_file_extensions:
  - .tsx
  - .ts
  - .js
  import_aliases:
  - "@zen/": src/
  ignore_dependencies_containing:
  - node_modules
  ignore_files_containing:
  - .spec.ts
  - .spec.tsx
  - .story.ts
  - .story.tsx
  - .mock.ts
  - .mock.tsx
  - .snap
  - .gql
  - .generated.ts
  file_scan:
  - number_of_methods
  - source_lines_of_code
  - dependency_graph
  - fan_in_out
  - louvain_modularity
  export:
  - directory: ./report/
  - graphml
  - dot
  - json
  - tabular_file
  - tabular_console_overall
  - d3
```

Notice that I exclude all `spec` files, yet I see in console:
```
2021-12-06 23:56:20     parser D ⏩ extracting imports from base result SettingsRepository.spec.ts...
2021-12-06 23:59:44     parser D ⏩ extracting imports from base result CaptureProfileRolesPage.spec.tsx...
```

I would expect those to be excluded?
