### ISSUE TITLE
Test files are included in the output

### ISSUE THREAD

**Issue by rafaelrozon** [glato/emerge#49]
**Describe the bug**
I'm trying to exclude test files and other kinds of files from the output graph, but they are always present. 

**Describe your environment**
- Are you using the tool on macOS or linux? _macOS_
- Which Python version are you using? _Python 3.9.6_
- Which browser (with version) are you using? _Chrome 121.0.6167.184_
- Are you scanning a public source code repository that you can provide? _I tried this in a private repo and in a public repo. The results were the same. This is the public repo I used for testing: https://github.com/resend/react-email_
- If not - can you provide code snippets where or further information on the data that might be relevant for the bug?

**To Reproduce**
1. Create a config like
```yml
project_name: react-email-analysis
loglevel: info
analyses:
- analysis_name: react email analysis
  source_directory:  /tmp/emerge/packages
  only_permit_languages:
  - typescript
  only_permit_file_extensions:
  - .ts
  - .tsx
  ignore_files_containing:
  - .spec.tsx
  ignore_dependencies_matching:
  - (.*)\.spec\.tsx
  file_scan:
  - number_of_methods
  - source_lines_of_code
  - dependency_graph
  - fan_in_out
  - louvain_modularity
  - tfidf
  export:
  - directory:  /tmp/emerge/export
  - graphml
  - json
  - tabular_file
  - tabular_console_overall
  - d3
```
3. Run the tool
```bash
docker run --rm -v <full path to the root of the project cloned on machine>:/tmp/emerge achtelik/emerge:2.0.0 /tmp/emerge/config.yml
```
5. Once emerge is done, open the emerge.html page generated
6. See that test files (`.spect.tsx`) are in the graph

**Expected behavior**
Any file filtered by the config options `ignore_files_containing` and `ignore_dependencies_matching` is not present in the output.

**Screenshots**
![Screenshot 2024-02-18 at 07 03 58](https://github.com/glato/emerge/assets/4046174/242d7042-7587-438f-8c55-5b41a9c0e3ef)

**Additional context**

Thanks!
