### ISSUE TITLE
FileNotFoundError: graph_representations_d3_force_graph.js

### ISSUE THREAD

**Issue by kargaranamir** [glato/emerge#6]
Hi, I got this error when I used `d3` in YAML config on my java code. 

```    
with open(target_export_file_path, 'w') as file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/amir/emerge_test/export/force-graph-html/resources/js/graph_representations_d3_force_graph.js'
```
Thanks.

Should the emerge.py and my java code be in the same directory?  I can have other output formats when i call emerge.py from another location (its source) but it seems it doesn't work for `d3` format when they are not in the same directory.

**Comment by glato** [comment]
@kargaranamir  Thanks for the report, I'll have a look at this. There could be a bug in `export.py` / `D3Exporter` when trying to write `target_export_file_path`. Could you maybe paste you whole YAML config so I could try to reproduce this?

**Comment by kargaranamir** [comment]
Thanks for your help, I will look forward to hearing from you. 
When I put my code in the same directory with emerge.py everything is ok (every possible output), but when I call emerge.py from its source in another location I can not get the `d3` format and it makes an error (but I can get the other formats if I remove `d3`). 

Config:

```
---
project_name: 10_water-simulator
loglevel: info
analyses:
- analysis_name: full java check
  source_directory: /home/amir/emerge_test
  only_permit_languages:
  - java
  only_permit_file_extensions:
  - .java
  file_scan:
  - number_of_methods
  - source_lines_of_code
  - dependency_graph
  - fan_in_out
  - louvain_modularity
  entity_scan:
  - dependency_graph
  - inheritance_graph
  - complete_graph
  - source_lines_of_code
  - number_of_methods
  - fan_in_out
  - louvain_modularity
  export:
  - directory: /home/amir/emerge_test/export
  - graphml
  - dot
  - json
  - tabular_file
  - tabular_console_overal
```
